### ISSUE TITLE
Npgsql error on some inputs tables

### ISSUE THREAD

**Issue by IoannaTsakalakidou** [Geodan/pg2b3dm#120]
I run  `pg2b3dm` using different postgis tables as input. The error occurs only on some of them and the resulting output varies. Specifically, these are the different outcomes I get:

- Case 1 (Works as expected): outputs `content`, `subtrees`, `tileset.json`
- Case 2: outputs `content`
- Case 3: no outputs at all

#### Case 2 error: 

```
Tool: pg2b3dm 1.8.2.0
Start processing 2023-10-04T15:43:37....
Input table: brabant_limburg_49o_final
Input geometry column: geom_triangle
Spatial reference of brabant_limburg_49o_final.geom_triangle: 4978
Spatial index detected on brabant_limburg_49o_final.geom_triangle
Query bounding box of brabant_limburg_49o_final.geom_triangle...
Bounding box for brabant_limburg_49o_final.geom_triangle (in WGS84): 4,2897, 51,3464, 4,6119, 51,5971
Default color: #FFFFFF
Default metallic roughness: #008000
Doublesided: True
Create glTF tiles: True
Attribute columns: lithoklasse,lithostrat,kans_1_veen,kans_2_klei,kans_3_kleiig_zand,kans_4_vervallen,kans_5_zand_fijn,kans_6_zand_matig_grof,kans_7_zand_grof,kans_8_grind,kans_9_schelpen
Starting Cesium mode...
Translation: 3969101,308946,90625,4966406
Lod column:
Geometric errors: 2000,0
Geometric error used for implicit tiling: 2000
Heights for bounding volume: [0 m, 100 m]
Add outlines: False
Use 3D Tiles 1.1 implicit tiling: True
Maximum features per tile: 1000
Start generating tiles...
Creating tile: 7_121_63.glb  Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.TimeoutException: Timeout during reading attempt
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|233_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at B3dm.Tileset.FeatureCountRepository.CountFeaturesInBox(NpgsqlConnection conn, String geometry_table, String geometry_column, Point from, Point to, Int32 epsg, String query) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\FeatureCountRepository.cs:line 16
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, Double areaTolerance, String defaultColor, String defaultMetallicRoughness, Boolean doubleSided, Boolean createGltf) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\QuadtreeTiler.cs:line 58
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, Double areaTolerance, String defaultColor, String defaultMetallicRoughness, Boolean doubleSided, Boolean createGltf) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\QuadtreeTiler.cs:line 84
   at pg2b3dm.Program.<>c__DisplayClass4_0.<Main>b__0(Options o) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 176
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at pg2b3dm.Program.Main(String[] args) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 29
```

#### Case 3 error:

```
Tool: pg2b3dm 1.8.2.0
Start processing 2023-10-04T15:16:18....
Input table: brabant_limburg_50o_final
Input geometry column: geom_triangle
Spatial reference of brabant_limburg_50o_final.geom_triangle: 4978
Spatial index detected on brabant_limburg_50o_final.geom_triangle
Query bounding box of brabant_limburg_50o_final.geom_triangle...
Bounding box for brabant_limburg_50o_final.geom_triangle (in WGS84): 4,8601, 51,3609, 5,1972, 51,6013
Default color: #FFFFFF
Default metallic roughness: #008000
Doublesided: True
Create glTF tiles: True
Attribute columns: lithoklasse,lithostrat,kans_1_veen,kans_2_klei,kans_3_kleiig_zand,kans_4_vervallen,kans_5_zand_fijn,kans_6_zand_matig_grof,kans_7_zand_grof,kans_8_grind,kans_9_schelpen
Starting Cesium mode...
Translation: 3964976,25,348887,5,4967051,5
Lod column:
Geometric errors: 2000,0
Geometric error used for implicit tiling: 2000
Heights for bounding volume: [0 m, 100 m]
Add outlines: False
Use 3D Tiles 1.1 implicit tiling: True
Maximum features per tile: 1000
Start generating tiles...
Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.TimeoutException: Timeout during reading attempt
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|233_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at B3dm.Tileset.FeatureCountRepository.CountFeaturesInBox(NpgsqlConnection conn, String geometry_table, String geometry_column, Point from, Point to, Int32 epsg, String query) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\FeatureCountRepository.cs:line 19
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, Double areaTolerance, String defaultColor, String defaultMetallicRoughness, Boolean doubleSided, Boolean createGltf) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\QuadtreeTiler.cs:line 58
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, Double areaTolerance, String defaultColor, String defaultMetallicRoughness, Boolean doubleSided, Boolean createGltf) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\QuadtreeTiler.cs:line 84
   at pg2b3dm.Program.<>c__DisplayClass4_0.<Main>b__0(Options o) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 176
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at pg2b3dm.Program.Main(String[] args) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 29
```

#### Comments

 - The error is persistent for the same input. For example, each time I run the tool using an input table which gives an error of case 2, the error remains the same.
 - Table size seems to be relevant:
             - Case 1:  table size < ~ 6GB 
             - Case 2:  ~ 6GB < table size  < ~ 9,5GB
             - Case 3:  table size > ~ 9,5GB

#### Technical details
PostgreSQL version: 15.3.0
pg2b3dm version: 1.8.2

**Comment by bertt** [comment]
Increase —sql_command_timeout (default 30 seconds)?

**Comment by IoannaTsakalakidou** [comment]
Yes, that fixes it!

**Comment by bertt** [comment]
FYI, in release 1.8.3 the timeout is removed (also the —sql_command_timeout parameter)
