### ISSUE TITLE
v2.8.1 cannot render tube

### ISSUE THREAD

**Issue by skemaikin** [Geodan/pg2b3dm#165]
HI!
I have a test table with the LINESTRINGZ geometry. When I trying to run the utility I have got an error:

```
> docker run --rm -v $(pwd)/output:/app/output -it geodan/pg2b3dm:2.8.1 -h 192.168.0.250 -p 5432 -U postgres -d postgres -t test -c wkb_geometry

...

Creating tile: 0_0_0.glb  Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Wkx.Polygon' to type 'Wkx.PolyhedralSurface'.
   at B3dm.Tileset.GeometryRepository.GetGeometriesBoundingBox(NpgsqlConnection conn, String geometry_table, String geometry_column, Int32 epsg, Tile t, String query) in /src/b3dm.tileset/GeometryRepository.cs:line 30
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, String defaultColor, String defaultMetallicRoughness, Boolean doubleSided, Boolean createGltf) in /src/b3dm.tileset/QuadtreeTiler.cs:line 132
   at pg2b3dm.Program.<>c__DisplayClass2_0.<Main>b__0(Options o) in /src/pg2b3dm/Program.cs:line 187
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at pg2b3dm.Program.Main(String[] args) in /src/pg2b3dm/Program.cs:line 25

```
The table **test** has only columns: ogc_fid and wkb_geometry.
How to run **pg2b3dm** correctly to create the tube?

**Comment by bertt** [comment]
See https://github.com/Geodan/pg2b3dm/issues/162

**Comment by skemaikin** [comment]
Hi,
different Z works perfectly. 
Waiting for #164
