### ISSUE TITLE
Crash on timeout

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/pg2b3dm#28]
encountered a stalling process on a pgsql timeout:
Coincidentally the swap space of the machine ran full but not sure if this is related.

```
Writing 1421 tiles...
Progress: tile 253 - 17.80%
Unhandled Exception: Npgsql.NpgsqlException: Exception while reading from stream ---> System.IO.IOException: Unable to read data from the transport connection: Connection timed out. ---> System.Net.Sockets.SocketException: Connection timed out
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at Npgsql.NpgsqlReadBuffer.<>c__DisplayClass31_0.<<Ensure>g__EnsureLong|0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Npgsql.NpgsqlReadBuffer.<>c__DisplayClass31_0.<<Ensure>g__EnsureLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at pg2b3dm.BoundingBoxRepository.GetGeometrySubset(NpgsqlConnection conn, String geometry_table, String geometry_column, Double[] translation, Int32[] row_numbers, String colorColumn) in /src/pg2b3dm/BoundingBoxRepository.cs:line 80
   at pg2b3dm.Program.WriteTiles(NpgsqlConnection conn, String geometryTable, String geometryColumn, Double[] translation, Node node, String outputPath, String colorColumn) in /src/pg2b3dm/Program.cs:line 85
   at pg2b3dm.Program.WriteTiles(NpgsqlConnection conn, String geometryTable, String geometryColumn, Double[] translation, Node node, String outputPath, String colorColumn) in /src/pg2b3dm/Program.cs:line 98
   at pg2b3dm.Program.WriteTiles(NpgsqlConnection conn, String geometryTable, String geometryColumn, Double[] translation, Node node, String outputPath, String colorColumn) in /src/pg2b3dm/Program.cs:line 98
   at pg2b3dm.Program.WriteTiles(NpgsqlConnection conn, String geometryTable, String geometryColumn, Double[] translation, Node node, String outputPath, String colorColumn) in /src/pg2b3dm/Program.cs:line 98
   at pg2b3dm.Program.WriteTiles(NpgsqlConnection conn, String geometryTable, String geometryColumn, Double[] translation, Node node, String outputPath, String colorColumn) in /src/pg2b3dm/Program.cs:line 98
   at pg2b3dm.Program.WriteTiles(NpgsqlConnection conn, String geometryTable, String geometryColumn, Double[] translation, Node node, String outputPath, String colorColumn) in /src/pg2b3dm/Program.cs:line 98
   at pg2b3dm.Program.<>c.<Main>b__2_0(Options o) in /src/pg2b3dm/Program.cs:line 73
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at pg2b3dm.Program.Main(String[] args) in /src/pg2b3dm/Program.cs:line 79
```

**Comment by bertt** [comment]
is it  reproducible?

**Comment by tomvantilburg** [comment]
```
docker run \
        -v $(pwd)/data/tiles:/app/output \
        -it geodan/pg2b3dm \
        -h metis -U tomt -d maquette_nl -p 5433 \
        -t results.extruded_4978 \
        -r colors
```

**Comment by bertt** [comment]
default query timeout is 30 seconds, I guess query for tile 253 took longer. Trying to reproduce now.

**Comment by bertt** [comment]
cannot repro this:
![no_repro](https://user-images.githubusercontent.com/538812/63764723-c1624200-c8c7-11e9-8111-2e6496edc1b9.png)

can you retry and see if this happens at tile 253 again?

**Comment by tomvantilburg** [comment]
Works for me now. Likely coincided with out of memory problem on the server. 
```
Writing tileset.json...
Writing 1421 tiles...
Progress: tile 266 - 18.72%
```
