### ISSUE TITLE
generate tileset from shapefile failed

### ISSUE THREAD

**Issue by ali322** [Geodan/pg2b3dm#40]
i follow this guide https://github.com/Geodan/pg2b3dm/blob/master/getting_started.md#reproject-geometry-to-3857 to generate tileset

when i run `docker run -it --network mynetwork bertt/tesselate_building -h some-postgis -U postgres -d postgres -t delaware_buildings -i geom_3857 -o geom_triangle_3857 --idcolumn ogc_fid --stylecolumn style --colorscolumn colors`,i got such error
```bash
Unhandled exception. Npgsql.PostgresException (0x80004005): XX000: transform: couldn't project point (-8.40839e+06 4.74422e+06 0): latitude or longitude exceeded limits (-14)
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2797
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 568
   at tesselate_building_sample_console.Program.<>c__DisplayClass1_0.<Main>b__0(Options o) in /src/tesselate_building_sample_console/Program.cs:line 65
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at tesselate_building_sample_console.Program.Main(String[] args) in /src/tesselate_building_sample_console/Program.cs:line 78
  Exception data:
    Severity: ERROR
    SqlState: XX000
    MessageText: transform: couldn't project point (-8.40839e+06 4.74422e+06 0): latitude or longitude exceeded limits (-14)
    File: lwgeom_pg.c
    Line: 128
    Routine: pg_error
```

plz help

**Comment by bertt** [comment]
The getting started document is partly rewritten yesterday, that command is changed

**Comment by ali322** [comment]
i followed the newest gettting started document, but the generated tileset.json is quite different from the sample_data, any ideas?

**Comment by ali322** [comment]
in the live sample of cesium,roof is invisible and the wall is transparent

**Comment by bertt** [comment]
Hi I've fixed roof colors in Cesium see https://geodan.github.io/pg2b3dm/sample_data/delaware/cesium/

Also did some rewrite of getting started document. You can do 'docker pull geodan/pg2b3dm' and 'docker pull bertt/tesselate_building' to get the latest software versions.

**Comment by ali322** [comment]
everything works file, is there a way to put customized texture on roof or wall?

**Comment by bertt** [comment]
ok great. Support for custom glTF materials is not there yet.
