### ISSUE TITLE
Crash when not using attributes -a

### ISSUE THREAD

**Issue by bertt** [Geodan/pg2b3dm#51]
Sample without -a option:  -h localhost -U postgres -c geom_triangle -t delaware_buildings_3857_no_lod -d postgres -i id  -e 2000 -r colors -o tiles

Program is crashing:

```
%Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at pg2b3dm.Program.GetAttributes(List`1 geometries) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 162
   at pg2b3dm.Program.WriteTiles(NpgsqlConnection conn, String geometryTable, String geometryColumn, String idcolumn, Double[] translation, List`1 tiles, Int32 epsg, String outputPath, Int32 counter, Int32 maxcount, String colorColumn, String attributesColumn, String lodColumn) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 143
   at pg2b3dm.Program.<>c.<Main>b__1_0(Options o) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 101
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at pg2b3dm.Program.Main(String[] args) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 24

D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\bin\Debug\netcoreapp3.1\pg2b3dm.exe (process 26104) exited with code 0.
```

**Comment by bertt** [comment]
Fixed in https://github.com/Geodan/pg2b3dm/issues/51
