### ISSUE TITLE
pg2b3dm: Exception while connecting

### ISSUE THREAD

**Issue by enersis-pst** [Geodan/pg2b3dm#61]
What im doing wrong?
Use docker on Win10 with PowerShell

same error for a wrong ip or without `-h 127.0.0.1`

```
docker run -it -v ${PWD}/output:/app/output geodan/pg2b3dm -h 127.0.0.1 -U postgres -c geom -t lod2 -d postgres -i id --shaderscolumn color
tool: pg2b3dm 0.10.0.0
password for user postgres:
start processing....
input table:  lod2
input geometry column:  geom
output directory:  ./output/tiles
geometric errors: 500,0
Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
   at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlConnection.Open()
   at B3dm.Tileset.BoundingBoxRepository.GetBoundingBox3DForTable(NpgsqlConnection conn, String geometry_table, String geometry_column, String query) in /src/b3dm.tileset/BoundingBoxRepository.cs:line 31
   at pg2b3dm.Program.<>c.<Main>b__1_0(Options o) in /src/pg2b3dm/Program.cs:line 88
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at pg2b3dm.Program.Main(String[] args) in /src/pg2b3dm/Program.cs:line 24
```

`SELECT st_astext(geom), id, color FROM public.lod2;`

geom:
`POLYHEDRALSURFACE Z (((7.582985649336324 51.53392380052991 77.314,7.583014764087601 51.5338475198775 77.314,7.583042164344734 51.533891913092894 82.256,7.582985649336324 51.53392380052991 77.314)),((7.583212412682651 51.53387713581456 77.314,7.583183422196508 51.533953139253995 77.314,7.583155959927464 51.53390888020825 82.256,7.583212412682651 51.53387713581456 77.314)),((7.583014764087601 51.5338475198775 77.314,7.583212412682651 51.53387713581456 77.314,7.583155959927464 51.53390888020825 82.256,7.583014764087601 51.5338475198775 77.314)),((7.583042164344734 51.533891913092894 82.256,7.583014764087601 51.5338475198775 77.314,7.583155959927464 51.53390888020825 82.256,7.583042164344734 51.533891913092894 82.256)),((7.583183422196508 51.533953139253995 77.314,7.582985649336324 51.53392380052991 77.314,7.583042164344734 51.533891913092894 82.256,7.583183422196508 51.533953139253995 77.314)),((7.583155959927464 51.53390888020825 82.256,7.583183422196508 51.533953139253995 77.314,7.583042164344734 51.533891913092894 82.256,7.583155959927464 51.53390888020825 82.256)),((7.583212412682651 51.53387713581456 77.314,7.583014764087601 51.5338475198775 77.314,7.583014764087601 51.5338475198775 70.424,7.583212412682651 51.53387713581456 77.314)),((7.583212412682651 51.53387713581456 70.424,7.583212412682651 51.53387713581456 77.314,7.583014764087601 51.5338475198775 70.424,7.583212412682651 51.53387713581456 70.424)),((7.583014764087601 51.5338475198775 77.314,7.582985649336324 51.53392380052991 77.314,7.582985649336324 51.53392380052991 70.424,7.583014764087601 51.5338475198775 77.314)),((7.583014764087601 51.5338475198775 70.424,7.583014764087601 51.5338475198775 77.314,7.582985649336324 51.53392380052991 70.424,7.583014764087601 51.5338475198775 70.424)),((7.582985649336324 51.53392380052991 77.314,7.583183422196508 51.533953139253995 77.314,7.583183422196508 51.533953139253995 70.424,7.582985649336324 51.53392380052991 77.314)),((7.582985649336324 51.53392380052991 70.424,7.582985649336324 51.53392380052991 77.314,7.583183422196508 51.533953139253995 70.424,7.582985649336324 51.53392380052991 70.424)),((7.583183422196508 51.533953139253995 77.314,7.583212412682651 51.53387713581456 77.314,7.583212412682651 51.53387713581456 70.424,7.583183422196508 51.533953139253995 77.314)),((7.583183422196508 51.533953139253995 70.424,7.583183422196508 51.533953139253995 77.314,7.583212412682651 51.53387713581456 70.424,7.583183422196508 51.533953139253995 70.424)),((7.583183422196508 51.533953139253995 70.424,7.583014764087601 51.5338475198775 70.424,7.582985649336324 51.53392380052991 70.424,7.583183422196508 51.533953139253995 70.424)),((7.583183422196508 51.533953139253995 70.424,7.583212412682651 51.53387713581456 70.424,7.583014764087601 51.5338475198775 70.424,7.583183422196508 51.533953139253995 70.424)))`

color: #f5f5f5
id: helloWorld

**Comment by enersis-pst** [comment]
@bertt thanks.

looks like it coudnt connect to my local db. With a docker included db it could connect.

${PWD} works in Powershell.

now i get the next error:
```
D:\tmp\2021\citygml_convert> docker run -it --network mynetwork -v ${PWD}/output:/app/output geodan/pg2b3dm -h some-postgis -U postgres -c geom -t lod22 -d postgres -i id --shaderscolumn co
lor
tool: pg2b3dm 0.10.0.0
password for user postgres:
start processing....
input table:  lod22
input geometry column:  geom
output directory:  ./output/tiles
geometric errors: 500,0
spatial reference: 0
creating quadtree: 1/1 - 100.00%
tiles with features: 1
writing tileset.json...
creating tiles: 1/1 - 100.00%Unhandled exception. Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: #. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at B3dm.Tileset.BoundingBoxRepository.GetGeometrySubset(NpgsqlConnection conn, String geometry_table, String geometry_column, String idcolumn, Double[] translation, Tile t, Int32 epsg, String shaderColumn, String attributesColumn, String lodColumn) in /src/b3dm.tileset/BoundingBoxRepository.cs:line 91
   at pg2b3dm.Program.WriteTiles(NpgsqlConnection conn, String geometryTable, String geometryColumn, String idcolumn, Double[] translation, List`1 tiles, Int32 epsg, String outputPath, Int32 counter, Int32 maxcount, String colorColumn, String attributesColumn, String lodColumn) in /src/pg2b3dm/Program.cs:line 143
   at pg2b3dm.Program.<>c.<Main>b__1_0(Options o) in /src/pg2b3dm/Program.cs:line 104
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at pg2b3dm.Program.Main(String[] args) in /src/pg2b3dm/Program.cs:line 24
```

**Comment by enersis-pst** [comment]
i also have to change the coordinate system to 3857 right?
also same error

**Comment by bertt** [comment]
yes 3857 if the client is mapbox gl js.
looks like there is an error in the sahderscolumn, can you try to run without --shaderscolumn co ?

**Comment by enersis-pst** [comment]
yes without it works :-). Maybe because i only use color value and not a json object.

**Comment by bertt** [comment]
yes it needs to be a json object
