### ISSUE TITLE
Error on tiling with -f cesium option

### ISSUE THREAD

**Issue by muratkendir** [Geodan/pg2b3dm#72]
Hi,
I have tested the tool with a small subset from delaware sample dataset and getting error below.
I have tried to use -f cesium option with the tesselate_building tool
My configuration is:
PostgreSQL 14.1 + PostGIS 3.1 (SFCGAL Extension created)

Do you have any idea about the error?

`C:\Users\murat\Downloads\geodan-test\Delaware>pg2b3dm -h localhost -U postgres -c geom_triangle -t delaware_buildings -d geodan -i id --shaderscolumn shaders
tool: pg2b3dm 0.11.2.0
password for user postgres:
start processing....
input table:  delaware_buildings
input geometry column:  geom_triangle
output directory:  ./output\tiles
geometric errors: 500,0
spatial reference: 4978
attributes columns:
creating quadtree: 1/1 - 100,00%Unhandled exception. Npgsql.PostgresException (0x80004005): 42883: function st_makeenvelope(integer, bigint, integer, integer, integer, bigint, integer, integer, integer) does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteReader()
   at B3dm.Tileset.BoundingBoxRepository.HasFeaturesInBox(NpgsqlConnection conn, String geometry_table, String geometry_column, Point from, Point to, Int32 epsg, String lodQuery) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\BoundingBoxRepository.cs:line 20
   at B3dm.Tileset.TileCutter.GetTiles(Int32 tileId, NpgsqlConnection conn, Double extentTile, String geometryTable, String geometryColumn, BoundingBox3D box3d, Int32 epsg, Int32 currentLod, List`1 lods, Double[] geometricErrors, String lodcolumn, String query) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\TileCutter.cs:line 37
   at pg2b3dm.Program.<>c.<Main>b__1_0(Options o) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 96
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at pg2b3dm.Program.Main(String[] args) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 23
  Exception data:
    Severity: ERROR
    SqlState: 42883
    MessageText: function st_makeenvelope(integer, bigint, integer, integer, integer, bigint, integer, integer, integer) does not exist
    Hint: No function matches the given name and argument types. You might need to add explicit type casts.
    Position: 121
    File: parse_func.c
    Line: 636
    Routine: ParseFuncOrColumn`

**Comment by bertt** [comment]
Hi, this looks like something with decimal separator, can you set decimal symbol to dot '.' and try again?

![image](https://user-images.githubusercontent.com/538812/148031684-0f96af94-1042-4219-91e3-6cd19cd25eba.png)

**Comment by muratkendir** [comment]
You have right, the problem was about decimal seperator. 
I forget to look for the regional settings as usual suspects:)
Thanks...

**Comment by tobias-brunner** [comment]
it is already set to 'dot'... 
![image](https://user-images.githubusercontent.com/7847517/148547794-447970a4-fd18-4e08-896b-578d692e97fd.png)
