### ISSUE TITLE
 I don't know what error

### ISSUE THREAD

**Issue by sanggwon** [Geodan/pg2b3dm#95]
C:\Users\ck257\Desktop\demo>pg2b3dm -h localhost -U postgres -c geom -t bldg_footprints -d postgis -a id,height
Tool: pg2b3dm 1.5.3.0
Password for user postgres:
Start processing 2023-05-30T17:54:51....
Input table: bldg_footprints
Input geometry column: geom
Lod column:
Geometric errors: 2000,0
Geometric error used for implicit tiling: 2000
Spatial reference of bldg_footprints.geom: 4326
Query bounding box of bldg_footprints.geom...
Bounding box for bldg_footprints.geom (in WGS84): -88.2759, 30.5239, -84.9941, 32.5019
Heights for bounding volume: [0 m, 100 m]
Add outlines: False
Default color: #FFFFFF
Default metallic roughness: #008000
Translation: -9644163.63380203,3699535.982277431
Use 3D Tiles 1.1 implicit tiling: True
Attribute columns: id,height
Maximum features per tile: 1000
Start generating tiles...
Creating tile: 6_0_1.b3dm  Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at B3dm.Tileset.GeometryRepository.GetGeometryColumn(String geometry_column, Double[] translation) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\GeometryRepository.cs:line 88
   at B3dm.Tileset.GeometryRepository.GetSqlSelect(String geometry_column, Double[] translation, String shaderColumn, String attributesColumns) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\GeometryRepository.cs:line 74
   at B3dm.Tileset.GeometryRepository.GetGeometrySubset(NpgsqlConnection conn, String geometry_table, String geometry_column, Double[] translation, Tile t, Int32 epsg, String shaderColumn, String attributesColumns, String query) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\GeometryRepository.cs:line 42
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, Double areaTolerance, String defaultColor, String defaultMetallicRoughness) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\QuadtreeTiler.cs:line 98
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, Double areaTolerance, String defaultColor, String defaultMetallicRoughness) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\QuadtreeTiler.cs:line 84
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, Double areaTolerance, String defaultColor, String defaultMetallicRoughness) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\QuadtreeTiler.cs:line 84
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, Double areaTolerance, String defaultColor, String defaultMetallicRoughness) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\QuadtreeTiler.cs:line 84
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, Double areaTolerance, String defaultColor, String defaultMetallicRoughness) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\QuadtreeTiler.cs:line 84
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, Double areaTolerance, String defaultColor, String defaultMetallicRoughness) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\QuadtreeTiler.cs:line 84
   at pg2b3dm.QuadtreeTiler.GenerateTiles(BoundingBox bbox, Tile tile, List`1 tiles, Int32 lod, Boolean addOutlines, Double areaTolerance, String defaultColor, String defaultMetallicRoughness) in D:\dev\github.com\geodan\pg2b3dm\src\b3dm.tileset\QuadtreeTiler.cs:line 84
   at pg2b3dm.Program.<>c__DisplayClass3_0.<Main>b__0(Options o) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 148
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at pg2b3dm.Program.Main(String[] args) in D:\dev\github.com\geodan\pg2b3dm\src\pg2b3dm\Program.cs:line 28

**Comment by bertt** [comment]
you can follow https://github.com/Geodan/pg2b3dm/blob/master/getting_started.md, at line 'Spatial reference' it should be 4978 instead of 4326

**Comment by sanggwon** [comment]
thank you. i succeeded in creating the file.
Could you possibly work with adding elevation values?

**Comment by bertt** [comment]
yes for that add terrain height to the geometries

**Comment by sanggwon** [comment]
Thank you very much for your reply.

The elevation values ​​of the buildings are all made constant.
I want the height values ​​of each building to be modeled differently.
For example, to make a difference between a building on a slope and a building not on a slope.
Would that be possible?
May I ask for an example source?
